export const manCommissionGroups = {
  'RWS': [
    'BASLAG, EVELYN',
    'CALOPEZ, MERY JORGIE',
    'CAMANCE, MARILOU',
    'CARMELITA CATUBAY',
    'GARAN, ANALIZA',
    'MONTILLANO, VEA',
    'QUISIMONDO, JOAN',
    'ROQUESA, PRINCIPAL',
    'ROSELITO, COYOCA',
    'SAPANTA, MARY QUEEN',
    'RODELYN L SENO',
    'SILVA, MARILOU',
    'TORREGOSA, JUCEL'
  ],
  'PNP COMMISION': [
    'RAQUEL, ALBARACIN',
    'LUTARIO TAMARION',
    'GEORGINA OBSEQUIAS',
    'HAYANISAH SAIPODEN',
    'SOON, CHERYL',
    'LATONIO, DONABEL',
    'LIBRADILLA, ARCEL',
    'LIBONGCOGON, PERCEVERANDA',
    'HERMOSILLA, LISALITA',
    'HOYOHOY, ADELA',
    'DELFIN, MARIA NITA'
  ],
  'COORDINATOR: GROUP C': [
    'ANNALYN OCHEA',
    'TAURAC, NORHIDA IHT',
    'TORILLAS, JOSEPHINE JOY'
  ],
  'SPVR-MOLLY': [
    'ESTELA B. PANUNCIAL',
    'CHYROS ROA',
    'MA. GENALE T. ORTEGA',
    'MARILOU GICANO',
    'MARICEL INGENTE',
    'SHEILA MARIE N. ROMARATE',
    'MARIANNE BERNALES',
    'TIRSO M. LUCERNAS JR.',
    'GERALDINE CALDITO',
    'HAZEL R. MINGUITO',
    'MA. LIBERTY S. LAMBO',
    'JIA CHRISTI MANATAD',
    'MARY ANN Y. PEVIDA',
    'JENNIFER S. FRANCISCO',
    'ABNER I. FRANCISCO',
    'RODEL B. ORIONDO',
    'NARYL MAE TUÑACAO',
    'LIEZL L. PUNSALAN',
    'MARK ROSAL TIBON',
    'JENEFER B. CHAVEZ',
    'JENELY A. SIATON',
    'ALEXIS GARCIA',
    'LESLIE S. DESABILLE',
    'ANNABEL T. BORRINAGA',
    'FABIAN G. MEDINA',
    'JANET ARCENAL',
    'JIMMY ANCHERO',
    'ORVEN E. ESTRADA',
    'ALBERT T. PUNSALAN',
    'JERSON AMAD',
    'ANALYN P. CAYASAN',
    'ENY PONGASE',
    'LORY ANN RABADON',
    'CARMEL MATUNOG',
    'ROBINALDO SINOGBUHAN'
  ],
  'COORDINATOR: LONGWIND': [
    'JOANE DUMALAGAN'
  ],
  'COORDINATOR: KAPITAN': [
    'GAVIOLA, REYMARK'
  ],
  'COORDINATOR: GROUP D': [
    'JUDY ANN FUENTES'
  ],
  'COORDINATOR: GROUP G': [
    'MARY ANN, CATIPAY'
  ],
  'COORDINATOR: GROUP EDIK': [
    'UROT, MERCEDITA'
  ],
  'SPVR-APPLE': [
    'CABALLERO, EVANGELINE',
    'Yoly Baculi',
    'MIRAFLOR MANATAD',
    'Clarice Mae Arnilla',
    'Merilyn Gabutero'
  ]
};
